CREATE TABLE ad.skin_element
(
    id bigint(20) unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
    sid int(10) unsigned NOT NULL,
    type varchar(20) COMMENT '元素类型',
    img_src varchar(1000) COMMENT '图片地址',
    video_src varchar(1000) COMMENT '视频地址',
    `left` int(10) COMMENT 'x轴',
    top int(10) COMMENT 'y轴',
    width int(10) COMMENT '宽',
    height int(10) COMMENT '高',
    line_height int(10) COMMENT '行高',
    animated_name varchar(30) COMMENT '动画名称',
    duration int(10) COMMENT '持续时间',
    delay int(10),
    playing tinyint(1),
    `loop` tinyint(1),
    opacity int(3) COMMENT '透明度',
    transform int(3) COMMENT '旋转角度',
    text text COMMENT '文本',
    text_align varchar(10) COMMENT '文本位置',
    icon_key varchar(30) COMMENT '图标编号',
    bg varchar(500) COMMENT '背景',
    font_size int(3) COMMENT '字体大小',
    font_family varchar(30) COMMENT '字体',
    font_weight varchar(30) COMMENT '字体粗度',
    color varchar(30) COMMENT '字体颜色',
    zindex int(10),
    extend varchar(500) COMMENT '扩展字段',
    reality_type varchar(10) COMMENT '实际类型',
    temp tinyint(1) DEFAULT '0' COMMENT '0.普通元素 1.模板',
    edit tinyint(1) DEFAULT '1' COMMENT '0.不可编辑 1.可编辑',
    location varchar(10) COMMENT '默认位置',
    CONSTRAINT SKIN_FK FOREIGN KEY (sid) REFERENCES ad.skin (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX SKIN_FK ON ad.skin_element (sid);
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (30, 5, 'pic', 'material/1540433472443.png', null, 0, 1722, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 1, '公交路线', 'line', 1, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (31, 5, 'pic', 'material/1540544342469.png', null, 112, 416, 131, 31, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 2, '日期', 'date', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (32, 5, 'pic', 'material/1540544520310.png', null, 241, 366, 116, 38, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 3, '天气', 'wether', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (33, 5, 'pic', 'material/1540545838796.png', null, 352, 363, 118, 39, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 4, '噪音', 'zaoyin', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (34, 5, 'pic', 'material/1540546280965.png', null, 114, 320, 118, 39, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 5, '湿度', 'shidu', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (35, 5, 'pic', 'material/1540546323010.png', null, 233, 379, 122, 42, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 6, 'pm2.5', 'pm25', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (36, 5, 'pic', 'material/1540548097085.png', null, 0, 517, 1079, 360, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 7, '广告', 'ad', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (37, 5, 'pic', 'material/1540548415127.png', null, 0, 0, 64, 23, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 8, '星期', 'week', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (38, 5, 'pic', 'material/1540548651506.png', null, 82, 29, 135, 37, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 9, '时间', 'time', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (39, 5, 'text', null, null, 242, 63, 311, 80, 1, null, 1, 0, 0, 0, 100, 0, '古城外站', 'center', null, null, 44, '微软雅黑', 'bold', '#000000', 10, '标题', 'title', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (40, 5, 'pic', 'material/1540550617916.jpg', null, 0, 0, 1080, 396, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 11, '操控区域', 'ctrl', 1, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (46, 7, 'pic', 'material/1540548097085.png', null, 1, 100, 1079, 434, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 1, '广告', 'ad', 0, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (47, 7, 'pic', 'material/1540433472443.png', null, 0, 1722, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 2, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (48, 7, 'pic', 'material/1540433472443.png', null, 0, 1524, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 3, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (49, 7, 'pic', 'material/1540433472443.png', null, 0, 1326, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 4, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (50, 7, 'pic', 'material/1538993669355.jpg', null, 0, 2, 1081, 98, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 5, null, null, 0, 0, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (51, 7, 'text', null, null, 390, 25, 311, 80, 1, null, 1, 0, 0, 0, 100, 0, '古城外站', 'center', null, null, 44, '微软雅黑', 'bold', '#FFF9F9', 6, '标题', 'title', 0, 1, 'top');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (52, 7, 'pic', 'material/1540433472443.png', null, 0, 1128, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 7, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (53, 7, 'pic', 'material/1540433472443.png', null, 0, 930, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 8, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (54, 7, 'pic', 'material/1540433472443.png', null, 0, 732, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 9, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (55, 7, 'pic', 'material/1540433472443.png', null, 0, 534, 1080, 198, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 10, '公交路线', 'line', 0, 0, 'bottom');
INSERT INTO ad.skin_element (id, sid, type, img_src, video_src, `left`, top, width, height, line_height, animated_name, duration, delay, playing, `loop`, opacity, transform, text, text_align, icon_key, bg, font_size, font_family, font_weight, color, zindex, extend, reality_type, temp, edit, location) VALUES (56, 7, 'pic', 'material/1540544342469.png', null, -5, 1, 207, 40, 0, null, 1, 0, 0, 0, 100, 0, null, 'left', null, null, 18, '微软雅黑', 'normal', '#000000', 11, null, null, 0, 0, 'top');